// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEzdiwLZY85cz1jrUyZfP-8WxgrTKuu7U',
    appId: '1:227452934158:web:364fcaff12622c4be5c45f',
    messagingSenderId: '227452934158',
    projectId: 'firestore-database-eg',
    authDomain: 'firestore-database-eg.firebaseapp.com',
    storageBucket: 'firestore-database-eg.appspot.com',
    measurementId: 'G-Q586KKPCK9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDARZdm3qlgJ6AMDRzxiGl_WGFmWNUoJ0g',
    appId: '1:227452934158:android:61d7968899ed30e0e5c45f',
    messagingSenderId: '227452934158',
    projectId: 'firestore-database-eg',
    storageBucket: 'firestore-database-eg.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBToPM57Szol2WbW1iLCpCmA3_xx8zhYM',
    appId: '1:227452934158:ios:0acbab04de0cbe5ce5c45f',
    messagingSenderId: '227452934158',
    projectId: 'firestore-database-eg',
    storageBucket: 'firestore-database-eg.appspot.com',
    iosBundleId: 'com.example.firestoreDatabase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBToPM57Szol2WbW1iLCpCmA3_xx8zhYM',
    appId: '1:227452934158:ios:938119d7e2361d36e5c45f',
    messagingSenderId: '227452934158',
    projectId: 'firestore-database-eg',
    storageBucket: 'firestore-database-eg.appspot.com',
    iosBundleId: 'com.example.firestoreDatabase.RunnerTests',
  );
}
